version: 2.1
orbs:
  heroku: circleci/heroku@1.0.1
      
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - run:
          name: Storing previous commit
          command: |
            git rev-parse HEAD > ./commit.txt
      - heroku/install
      
workflows:
  build-test-deploy:
      - deploy:
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - main
